### ISSUE TITLE
Project Generator

### ISSUE THREAD

**Issue by MatthewSH** [adapap/OWScript#16]
I think the biggest thing for newcomers to OWS will be: "how do I setup my project?" If we implement something like #15 then it could help standardize it, but maybe we should go a step further and have a generator or some for of global package (this can be written in nodejs for all I care) that can do the following:

1. Generate the base project file
2. Initiate git
   - If git is initiated, add OWScript latest release as a submodule or latest commit on master branch
    - If git is not initiated, download and extract the latest release or master to the project directory
3. Create the base json configuration file.
4. Setup a source directory (`src`) with an example file inside it

**Comment by adapap** [comment]
@MatthewSH Will there be anything added to this repo, even if in another branch? Otherwise I can add the npm package to the readme and close this issue.

**Comment by netux** [comment]
I have a different idea for this: how about uploading OWScript to pip and including the project generation code there?

It makes the setup easy and intuitive; something like running `pip install OWScript`, create the folder you want to setup your project in, and run `OWScript init`

**Comment by MatthewSH** [comment]
@adapap we can probably close this out since I’m working in another repo. 

@netux it really just comes down to preference. I personally like TypeScript and NPM for it, but if someone wanted to create a pip version then for for it. I just, personally, have more experience in NPM/global package development.
